apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  serviceName: "{{ .Values.name }}"
  replicas: 6
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: redis:7.0.5
        command: ['/bin/bash', '-c', 'cp -f -r /redis/conf/..data/* /etc/; redis-server /etc/redis.conf']
        volumeMounts:
        - name: {{ .Values.name }}-conf
          mountPath: /redis/conf
      volumes:
        - name: {{ .Values.name }}-conf
          configMap:
            name: {{ .Values.name }}-conf
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - port: {{ .Values.port }}
    name: {{ .Values.name }}-client
  - port: 1{{ .Values.port }}
    name: {{ .Values.name }}-cluster
  clusterIP: None