apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
data:
  redis.conf: |-
    port {{ .Values.port }}
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 3000
    appendonly yes
