apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ .Values.name }}
spec:
    serviceName: {{ .Values.name }}
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.name }}
        spec:
            containers:
            - name: {{ .Values.name }}
              image: localhost:32000/clt-test-api-8m:0.1.0
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.name }}
    labels:
        app: {{ .Values.name }}
spec:
    selector:
        app: {{ .Values.name }}
    type: NodePort
    ports:
    - port: 8080
      nodePort: 30000
      name: {{ .Values.name }}