apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
data:
  redis.conf: |-
    port {{ .Values.port }}
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 3000
    appendonly yes
    cluster-preferred-endpoint-type hostname
    tcp-keepalive 0
    tcp-backlog 65536
  runner.sh: |-
    #!/bin/bash
    redis-cli --cluster create redis-master-0:6379 redis-master-1:6379 redis-master-2:6379 redis-master-3:6379