apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hd-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: namenode.hadoop.{{ .Values.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.name }}
            port: 
              number: 9870
  - host: resource-manager.hadoop.{{ .Values.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.name }}
            port: 
              number: 8088
  - host: job-history.hadoop.{{ .Values.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.name }}
            port: 
              number: 19888 
  # - host: tl.{{ .Values.hostname }}
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: /
  #       backend:
  #         service:
  #           name: {{ .Values.name }}
  #           port: 
  #             number: 8188    
