apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hd-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: namenode.{{ .Values.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.name }}
            port: 
              number: 9870
  - host: resourcemanager.{{ .Values.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.name }}
            port: 
              number: 8088
  - host: jobhistory.{{ .Values.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.name }}
            port: 
              number: 19888    