apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  serviceName: {{ .Values.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: raltlsdn/hadoop-base:3.3.4
        volumeMounts:
        - name: {{ .Values.name }}-dn
          mountPath: /hadoop/datanode
        - name: {{ .Values.name }}-nn
          mountPath: /hadoop/namenode
        - name: {{ .Values.name }}-conf
          mountPath: /hadoop/conf
        command: ['/bin/bash', '-c', 'service ssh start; . /root/.profile; /usr/bin/cp -f -r /hadoop/conf/..data/* /root/hadoop-3.3.4/etc/hadoop/;tail -f /dev/null']
      volumes:
      - name: {{ .Values.name }}-conf
        configMap:
          name: {{ .Values.name }}-conf
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.name }}-dn
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.dnvolume }}Gi
  - metadata:
      name: {{ .Values.name }}-nn
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.nnvolume }}Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - port: 22
    name: ssh
  - port: 8020
    name: nn
  - port: 8030
    name: rm-scheduler
  - port: 8031
    name: rm-tracker
  - port: 8032
    name: rm
  - port: 8050
    name: yarn-ipc
  - port: 8080
    name: jobtrack
  - port: 8088
    name: rm-web
  - port: 9000
    name: hdfs
  - port: 9001
    name: mapred
  - port: 9870
    name: nn-web
  - port: 10020
    name: jh-ipc
  - port: 19888
    name: jh-web
  # - port: 8188
  #   name: timeline-web
  # - port: 10200
  #   name: timeline-rpc